### ISSUE TITLE
UnknownError: "no reason specify"

### ISSUE THREAD

**Issue by itruivitorino** [OpenCTI-Platform/client-python#170]
## Description

Error when running "python misp.py", but the connect still keeps runnings.

## Environment

1. OS: Centos 7
2. OpenCTI version: 2.4.141
3. Python3.6.8
4. MISP {"major":2, "minor":4, "hotfix":142

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. python3 misp.py

## Expected Output

Yeh... never actually got past this.

## Actual Output

```
ERROR:root:No reason specify
Traceback (most recent call last):
  File "misp.py", line 1299, in <module>
    mispConnector.run()
  File "misp.py", line 160, in run
    self.helper.connect_id, friendly_name
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_work.py", line 72, in initiate_work
    query, {"connectorId": connector_id, "friendlyName": friendly_name}
  File "/usr/local/lib/python3.6/site-packages/pycti/api/opencti_api_client.py", line 275, in query
    {"name": error_name, "message": main_error["data"]["reason"]}
ValueError: {'name': 'UnknownError', 'message': 'No reason specify'}
```
 
## Additional information

config.json
```
opencti:
  url: 'http://IP:4000'
  token: 'TOKEN UUIv4'

connector:
  id: 'TOKEN UUIv4'
  type: 'EXTERNAL_IMPORT'
  name: 'MISP' # Required
  scope: 'misp'
  confidence_level: 15 # 0 (Unknown) or from 1 to 100
  update_existing_data: False
  log_level: 'debug'

misp:
  url: 'https://IP/' # Required
  reference_url: '' # Optional, will be used to create external reference to MISP event
  key: 'KEY UUIv4' # Required
```

I also get the CONNECTED status on the MISP dashboard, but when I try to send events (for example, python3 upload.py -u examples/dummy) the output seems okay but nothing goes to the dashboard, nor stdout.

I'm completly lost here.

**Comment by itruivitorino** [comment]
We can close this.
Problem with the permissions on the bucket of Redis Server.
