### ISSUE TITLE
[Stix2utils] SimpleObservable can't handle non-string "value" values

### ISSUE THREAD

**Issue by nor3th** [OpenCTI-Platform/client-python#186]
## Description

Using the SimpleObservable generic class, it is impossible to assign key values of another type than `string`

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: OpenCTI 4.5.4
3. Other environment details: 

## Reproducible Steps

```
obs = SimpleObservable(
    id=OpenCTIStix2Utils.generate_random_stix_id(
        "x-opencti-simple-observable"
    ),
    key='Autonomous-System.number',
    value=123,
    x_opencti_create_indicator=False,
)
opencti_api_client.stix2.import_observable(obs)

```

## Expected Output

Created ASN observable

## Actual Output

Output:
```
INFO:root:Creating Stix-Cyber-Observable {Autonomous-System} with indicator at False.
ERROR:root:Variable "$AutonomousSystem" got invalid value "123" at "AutonomousSystem.number"; Int cannot represent non-integer value: "123"
Traceback (most recent call last):
  File "/home/user/test.py", line 44, in <module>
    opencti_api_client.stix2.import_observable(obs)
  File "/home/user/.local/lib/python3.9/site-packages/pycti/utils/opencti_stix2.py", line 654, in import_observable
    stix_observable_result = self.opencti.stix_cyber_observable.create(
  File "/home/user/.local/lib/python3.9/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1060, in create
    result = self.opencti.query(query, input_variables)
  File "/home/user/.local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 276, in query
    raise ValueError(
ValueError: {'name': 'Variable "$AutonomousSystem" got invalid value "123" at "AutonomousSystem.number"; Int cannot represent non-integer value: "123"', 'message': 'Variable "$AutonomousSystem" got invalid value "123" at "AutonomousSystem.number"; Int cannot represent non-integer value: "123"'}
```
 
## Additional information

The value "123" is originally defined as integer and not as string, hence the problem must lie somewhere between my code snippet and the creation layer. I assume that the issue lies here, where the "value" value is converted to string.

https://github.com/OpenCTI-Platform/client-python/blob/3d7e94de483cd315ef674c7568ea6b9e016fea28/pycti/utils/opencti_stix2_utils.py#L73

Is there maybe a more dynamic approach to solving this issue with the conditional TypeProperty?

Same thing happens with Process IDs and the opencti score
```
ValueError: {'name': 'Variable "$Process" got invalid value "19000" at "Process.pid"; Int cannot represent non-integer value: "19000"', 'message': 'Variable "$Process" got invalid value "19000" at  "Process.pid"; Int cannot represent non-integer value: "19000"'}
ValueError: {'name': 'Variable "$x_opencti_score" got invalid value "90"; Int cannot represent non-integer value: "90"', 'message': 'Variable "$x_opencti_score" got invalid value "90"; Int cannot represent non-integer value: "90"'}

```

**Comment by nor3th** [comment]
I've looked into that issue a bit now and it seems that there is no dynamic way of doing that. Would it be a feasible approach to to define another CustomObservable like `SimpleIntObservable` which has an IntegerProperty as value? So instead of this
https://github.com/OpenCTI-Platform/client-python/blob/f75785e4cd6c249eb1db3dc53126cc0ca98370bb/pycti/utils/opencti_stix2_utils.py#L73
an IntegerProperty is defined
```
("value", properties.IntegerProperty(required=True)), 
```

Or another approach would be that somewhere in the course of the SCO transmission, the string value is converted to an int.
Any thoughts?
