### ISSUE TITLE
fetch_opencti_file Failure

### ISSUE THREAD

**Issue by r0sier** [OpenCTI-Platform/client-python#214]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

When using the fetch_opencti_file function, urllib3 throws the following error: 
`BlockingIOError: [Errno 11] Resource temporarily unavailable`

## Environment

PyCTI v5.0.2
OpenCTI v5.0.0

## Reproducible Steps

The following code results in the error:
```
opencti_api_client = OpenCTIApiClient(opencti_url, opencti_token)
inbound_file = opencti_api_client.fetch_opencti_file(url)
```

## Expected Output

File to be returned 

## Actual Output

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f38964b04c0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable
```

**Comment by nor3th** [comment]
Hey @r0sier 

It looks more like your script isn't able to establish a connection with OpenCTI. Can you try checking the connection and try running the API interactions again?

Regards
