### ISSUE TITLE
opencti_api_client.stix_cyber_observable.create - ValueError: {'name': 'Unknown type "StixId". Did you mean "StixFile"?', 'message': 'Unknown type "StixId". Did you mean "StixFile"?'}

### ISSUE THREAD

**Issue by lcia-projects** [OpenCTI-Platform/client-python#274]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

cannot create opencti observable even using example file. 

## Environment

1. OS (where OpenCTI server runs): ubuntu 20.04
3. OpenCTI version: latest
4. Other environment details:
have tried in both latest docker-compose and docker-dev while running opencti on host machine, same result

## Reproducible Steps

Steps to create the smallest reproducible scenario:
code: (from examples)
```
        observable_obj = self.opencti_api_client.stix_cyber_observable.create(
            **{
                "simple_observable_key": "IPv4-Addr.value",
                "simple_observable_value": "8.8.4.4",
            }
        )
```
or
```
url = opencti_api_client.stix_cyber_observable.create(
    observableData={"type": "IPv4-Addr.value", "value": "8.8.4.4"}
)

```

## Expected Output

observable object created

## Actual Output

ERROR:Unknown type "StixId". Did you mean "StixFile"?
Traceback (most recent call last):
  File "/Users/dm/Dropbox/Fusion Projects/Current Projects/ESlookoutQueryv2/main.py", line 29, in <module>
    openCTIInstance = libOpenCTIv2.openCTI(config, data)
  File "/Users/darrellmiller/Dropbox/Fusion Projects/Current Projects/ESlookoutQueryv2/libOpenCTIv2.py", line 15, in __init__
    self.processData()
  File "/Users/darrellmiller/Dropbox/Fusion Projects/Current Projects/ESlookoutQueryv2/libOpenCTIv2.py", line 26, in processData
    self.pD_observable(item, self.data[item])
  File "/Users/darrellmiller/Dropbox/Fusion Projects/Current Projects/ESlookoutQueryv2/libOpenCTIv2.py", line 194, in pD_observable
    observable_obj = self.opencti_api_client.stix_cyber_observable.create(
  File "/Users/darrellmiller/Dropbox/Fusion Projects/Current Projects/ESlookoutQueryv2/venv/lib/python3.9/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1134, in create
    result = self.opencti.query(query, input_variables)
  File "/Users/darrellmiller/Dropbox/Fusion Projects/Current Projects/ESlookoutQueryv2/venv/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 326, in query
    raise ValueError(
ValueError: {'name': 'Unknown type "StixId". Did you mean "StixFile"?', 'message': 'Unknown type "StixId". Did you mean "StixFile"?'}

## Additional information
this used to work, i've been using the python api for a couple of years now.

**Comment by richard-julien** [comment]
Your connector versions and the platform versions need to be aligned.
If you use a custom connector, you need to update it to use the aligned pycti with your deployed platform
