### ISSUE TITLE
Unknown type X509V3ExtensionsType

### ISSUE THREAD

**Issue by SYNchroACK** [OpenCTI-Platform/client-python#285]
## Description

```
# python script.py 
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Listing StixCyberObservables with filters null.
ERROR:root:Unknown type "X509V3ExtensionsType".
Traceback (most recent call last):
  File "/script.py", line 10, in <module>
    data = client.stix_cyber_observable.list(search="8.8.8.8")
  File "/pycti/entities/opencti_stix_cyber_observable.py", line 373, in list
    result = self.opencti.query(
  File "/pycti/api/opencti_api_client.py", line 314, in query
    raise ValueError(
ValueError: {'name': 'Unknown type "X509V3ExtensionsType".', 'message': 'Unknown type "X509V3ExtensionsType".'}
```

## Environment

2. OpenCTI version: 5.3.17

## Reproducible Steps

```
from pycti.utils.constants import StixCyberObservableTypes
from pycti import OpenCTIApiClient
import json

URL = "http://..."
TOKEN = "...."

client = OpenCTIApiClient(URL, TOKEN)

data = client.stix_cyber_observable.list(search="8.8.8.8")
print(json.dumps(data, indent=4))
```

**Comment by nor3th** [comment]
Hey @SYNchroACK 

The code to reproduce works for me, any chance your pycti and opencti platform version aren't the same?

Regards

**Comment by SYNchroACK** [comment]
Yup, I guess it was that. Now it also works for me. Sorry, I miss that important detail.
