### ISSUE TITLE
Importing OpenCTIApiClient causes the python interpreter to crash on any python error

### ISSUE THREAD

**Issue by BunnyApocalypse** [OpenCTI-Platform/client-python#292]
## Description

after opening a python interpreter, something is changed in the environment that causes the interpreter to be `sigkill`ed  after any error.

Ex:
```
user.name@hostname ~ % python3
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pycti import OpenCTIApiClient
>>> l
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'l' is not defined
zsh: killed     python3
```

This also happens on my personal Linux computer running Python3.11.0rc2 (Fedora 37) and BASH.

## Environment

OS: Fedora Linux 37 and Mac OS
pycti version 5.3.17

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a python interpreter `python` in terminal
3. run `from pycti import OpenCTIApiClient`
4. create an error, for example, reference something that doesnt exist: `l`

## Expected Output

Python gives the traceback but does not close the interpreter and you can keep messing around/debugging

## Actual Output

Python gives the traceback and then is sigkilled and you lose all debugging process you had made

## Additional information

Comparing an `strace` of an interpreter where I do not import OpenCTIApiClient with one where I do, I see that the environment with OpenCTIAPIClient immediately prints the traceback, runs a `getpid()` and then `kill([PID], SIGKILL)` whereas the normal interpreter does a lot of stuff before even printing the traceback.

I haven't had the time to look at the strace output and I am not sure I'd even find anything useful in there, but that might be useful to someone who has deeper knowledge of python than I do.

**Comment by BunnyApocalypse** [comment]
Thanks!

**Comment by BunnyApocalypse** [comment]
Still experiencing this on 5.4.0
```
[user]@[host] ~ % python3
Python 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkg_resources import get_distribution
>>> get_distribution('pycti')
pycti 5.4.0 (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages)
>>> import pycti
>>> bogus command
  File "<stdin>", line 1
    bogus command
          ^^^^^^^
SyntaxError: invalid syntax
zsh: killed     python3
```
