### ISSUE TITLE
[client] Cannot import STIX bundle using opencti_api_client.stix2.import_bundle

### ISSUE THREAD

**Issue by beerman17** [OpenCTI-Platform/client-python#650]
## Description

Hi there!

I am trying to submit a STIX bundle with single element of IPv4 observable using `opencti_api_client.stix2.import_bundle` method  and getting an error. 

## Environment

1. OS (where OpenCTI server runs): Mac OS 13.3.1
2. OpenCTI version: OpenCTI 6.1.0

## Reproducible Steps

Run the code:
```python
from pycti import OpenCTIApiClient
import stix2


OPENCTI_URL = 'http://localhost:4000'
OPENCTI_API_TOKEN = '<token>'

def main():

    opencti_api_client = OpenCTIApiClient(OPENCTI_URL, OPENCTI_API_TOKEN)
    stix_bundle = []
    # create observable
    observable = stix2.v21.observables.IPv4Address(
        value='1.1.1.1'
    )
    stix_bundle.append(observable)
    bundle = stix2.v21.Bundle(objects=stix_bundle, allow_custom=True)
    opencti_api_client.stix2.import_bundle(stix_bundle=bundle, update=True)
    return


if __name__ == '__main__':
    main()
```

## Expected Output

The observable was created in platform

## Actual Output

The error:
```
Traceback (most recent call last):
  File "<...>/src/main.py", line 59, in <module>
    main()
  File "<...>/src/main.py", line 53, in main
    opencti_api_client.stix2.import_bundle(stix_bundle=bundle, update=True)
  File "<...>/python3.10/site-packages/pycti/utils/opencti_stix2.py", line 2455, in import_bundle
    bundles = stix2_splitter.split_bundle(stix_bundle, False, event_version)
  File "<...>/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py", line 90, in split_bundle
    self.enlist_element(item["id"], raw_data)
  File "<...>/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py", line 56, in enlist_element
    item["nb_deps"] = nb_deps
TypeError: 'IPv4Address' object does not support item assignment
```

## Additional information

If I convert `stix2.Bundle` object to usual Python `Dict` the method works fine:
```python
    ...
    bundle = stix2.v21.Bundle(objects=stix_bundle, allow_custom=True).serialize()
    opencti_api_client.stix2.import_bundle(stix_bundle=json.loads(bundle), update=True)
    ...
```

It seem like a bug and the method should work with `stix2.Bundle` type as there is another method `opencti_api_client.stix2.import_bundle_from_json()` which supposed to be used (I guess) in case we have STIX bundle represented as dictionary.

**Comment by beerman17** [comment]
> We do not support today the direct usage of this bundle Oasis object.
> For now you have to I think to use **send_stix2_bundle(bundle.serialize())**
> Import bundle is use by the worker to process the bundle, in a connector you have to use the send_stix2_bundle.

Got it, thank you for the reply.
