### ISSUE TITLE
Python API  Analyzer/Observables Error

### ISSUE THREAD

**Issue by jfierro6** [OpenCTI-Platform/client-python#801]
## Description

{ When trying to use an analyzer/observable I get an error about 'Unknown type "Persona"' }

## Environment

1. OS OS - Flatcar Linux
2. OpenCTI version: 6.1.12
3. OpenCTI client: Python 6.4.4 
## Reproducible Steps

1. Run script / Error

```
Traceback (most recent call last):
  File "/worker/OpenCTI/opencti.py", line 114, in <module>
    OpenCTIAnalyzer().run()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/worker/OpenCTI/opencti.py", line 65, in run
    observables = opencti["api_client"].stix_cyber_observable.list(search=data)
  File "/usr/local/lib/python3.13/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 84, in list
    result = self.opencti.query(
        query,
    ...<8 lines>...
        },
    )
  File "/usr/local/lib/python3.13/site-packages/pycti/api/opencti_api_client.py", line 368, in query
    raise ValueError(value_error)
ValueError: {'name': 'Unknown type "Persona".', 'error_message': 'Unknown type "Persona".'}
```

## Additional info

Assuming that the 'OpenCTI CE : Secured W/ Nginx + Flatcar Linux' AMI from the AWS Market Place is a bit outdated, I went ahead and updated the OpenCTI connector to use version 6.4.4

**Comment by nino-filigran** [comment]
Could you please try to upgrade your OCTI platform, to ensure it matches the same version as your Client Python version and see if the problem remains? The issue might be that your two versions are different.

**Comment by nino-filigran** [comment]
Closing this issue since there is no activity on this ticket.
