### ISSUE TITLE
Possible race condiction in creation of observables and indicators

### ISSUE THREAD

**Issue by rhaist** [OpenCTI-Platform/client-python#90]
With the python client I still get random errors and I think it might be related to threading. 

## Description

If I ingest a lot of data from Malpedia in a short amount of time the indicator and observable create functions will return an incomplete object. If I rerun the object seems to created and the script continues.

It seems like the client returns before OpenCTI actually stored the entities and the returned JSON object is incomplete and parsing fails.

## Environment

Local testing with fresh instances of current OpenCTI versions in Docker.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Spawn new OpenCTI docker environment
2. Wait until web front end is available
3. Use the following script with the current pycti library to conduct a small load test

## Expected Output

No errors in sequential indicator creation.

## Actual Output

```
python3 test_indicators.py
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z81.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z82.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z83.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z84.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z85.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z86.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z87.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Listing Indicators with filters [{"key": "indicator_pattern", "values": ["[domain-name:value = 'www.5z88.info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']"], "operator": "eq"}].
INFO:root:Creating Indicator {C2 server of the new campaign}.
ERROR:root:error in API query: {'errors': [{'message': 'An unknown error has occurred!  Please try again later.', 'name': 'Unknown', 'time_thrown': '2020-05-07T19:58:17.701Z', 'data': {'type': 'technical', 'level': 'error'}}], 'data': {'indicatorAdd': None}}
Traceback (most recent call last):
  File "test_indicators.py", line 36, in <module>
    main()
  File "test_indicators.py", line 30, in main
    update=True,
  File "/Users/rha/git/client-python/pycti/entities/opencti_indicator.py", line 469, in create
    killChainPhases=kill_chain_phases,
  File "/Users/rha/git/client-python/pycti/entities/opencti_indicator.py", line 333, in create_raw
    return self.opencti.process_multiple_fields(result["data"]["indicatorAdd"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rhaist** [comment]
The script I used to conduct the test:
```
# coding: utf-8

from pycti.api.opencti_api_client import OpenCTIApiClient
from stix2 import TLP_AMBER, TLP_GREEN


def main():
    api_client = OpenCTIApiClient(
        "http://localhost:8080",
        "6db566a1-f1c5-4780-be3b-8d163067b890",
        ssl_verify=False,
    )

    i = 1

    while True:
        api_client.indicator.create(
            name="C2 server of the new campaign",
            description="This is the C2 server of the campaign",
            pattern_type="stix",
            indicator_pattern="[domain-name:value = 'www.5z8"
            + str(i)
            + ".info' AND domain-name:resolves_to_refs[*].value = '198.51.100.1/32']",
            main_observable_type="IPv4-Addr",
            confidence=60,
            score=80,
            detection=True,
            tags=["Test1", "Test2"],
            markingDefinitions=[TLP_AMBER["id"], TLP_GREEN["id"]],
            update=True,
        )
        i += 1


if __name__ == "__main__":
    main()

```

**Comment by SamuelHassine** [comment]
You cannot pass `markingDefinitions=[TLP_AMBER["id"], TLP_GREEN["id"]],`, if you change that with OpenCTI internal IDs of the marking definitions, your script runs correctly.

**Comment by SamuelHassine** [comment]
Use:

```
marking_definition_white = opencti_api_client.marking_definition.read(id=stix2.TLP_WHITE['id'])
```

Then pass marking_definition_white["id"]

**Comment by SamuelHassine** [comment]
PLease refer to: https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-platform/opencti-graphql/src/database/grakn.js#L1584

**Comment by SamuelHassine** [comment]
For the next release, we will support STIX ID of marking definitions at the creation, it is a tiny change.
